cnblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from cnblog import settings
from django.views.static import  serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^get_valid_img/', views.get_valid_img),
    url(r'^index/$', views.index),
    url(r'^$', views.index),
    url(r'^pc-geetest/register', views.pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^zhuce/', views.zhuce),
    url(r'^headp/', views.headp),
    url(r'^logout/', views.log_out),
    url(r'^(?P<username>\w+)/article/(?P<aid>\d+)', views.article),

    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),
    url(r'^index/(?P<para>\d+)',views.index),

    url(r'^up/$', views.up),
    url(r'^adelete/$', views.adelete),
    url(r'^backend/edit_article/(?P<id>\d+)$', views.edit_article),
    url(r'^down/$', views.down),
    url(r'^get_comment_tree/(\d+)$', views.get_comment_tree),
    url(r'^comment/$', views.comment),
    url(r'^backend/add_article/$', views.add_article),
    url(r'^backend/(?P<username>\w+)/$', views.backend),
    url(r'^backendd/$', views.backendd),
    url(r'^upload_img/',views.upload_img),
    url(r'^zblog/',views.zblog),
    url(r'^addcate/',views.addcate),
    url(r'^addtag/',views.addtag),
    url(r'^logedit/',views.logedit),



    # url(r'^comment/$', views.comment),
    # home_site(request,username="",condition="",para="")
    url(r'^(?P<username>\w+)/(?P<condition>tag|cate|archive)/(?P<para>.*)', views.home_site),
    url(r'^(?P<username>\w+)/$', views.home_site),  # home_site(request,username='yuan')





]

blog/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import AbstractUser
# Create your models here.
class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to = 'avatar/',default="avatar/default.jpg")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.OneToOneField(to='Blog', to_field='nid',null=True)

    def __str__(self):
        return self.username

class Blog(models.Model):

    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title

class HomeCategory(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title
class Tag(models.Model):

    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

class Article(models.Model):

    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')

    comment_count= models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    homeCategory = models.ForeignKey(to='HomeCategory', to_field='nid', null=True)
    siteDetaiCategory = models.ForeignKey(to='SiteDetaiCategory', to_field='id', null=True)
    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid')
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )


    def __str__(self):
        return self.title

class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()

    article = models.OneToOneField(to='Article', to_field='nid')

class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    parent_comment = models.ForeignKey('self', null=True)


    def __str__(self):
        return self.content

class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)
    is_up=models.BooleanField(default=True)
    is_down = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

class SiteCategory(models.Model):
    name=models.CharField(max_length=32)

    def __str__(self):
        return  self.name
class SiteDetaiCategory(models.Model):
    name=models.CharField(max_length=32)
    siteCategory=models.ForeignKey("SiteCategory")

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.forms import widgets
from .models import UserInfo
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
class RegForm(forms.Form):
    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request=request

    user=forms.CharField(min_length=5,max_length=12,
                         error_messages={"required": "用户名不能为空",
                             "min_length":"最小长度为5",
                                         "max_length": "最大长度为12" },
                         widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"5~12位不能为纯英文或纯数字"})
                         )
    pwd =forms.CharField(min_length=5,max_length=12,
                         error_messages={"required": "密码不能为空",
                             "min_length":"最小长度为5",
                                         "max_length": "最大长度为12" },
          widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"5~12位不能为纯英文或纯数字"})
    )

    repeat_pwd = forms.CharField(
        error_messages={"required": "密码验证不能为空"},
        widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "再次输入密码"})

    )

    email=forms.EmailField(error_messages={"invalid":"非邮箱格式！",
                                           "required": "邮箱不能为空"},
                           widget=widgets.EmailInput(attrs={"class": "form-control", "placeholder": "Email地址"})
                           )

    valid_code=forms.CharField(
        error_messages={"required": "验证码不能为空"},
        widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "valid_code"})
    )



    def clean_user(self):
        username = self.cleaned_data.get("user")
        if not username.isdigit() or not username.isalpha():
            user = UserInfo.objects.filter(username=self.cleaned_data.get("user"))
            if not user:
                return self.cleaned_data.get("user")

            else:
                raise ValidationError("用户名已经存在！")
        else:
            raise ValidationError("用户名不能是纯数字或者纯字母")

    def clean_pwd(self):
        pwd=self.cleaned_data.get("pwd")

        if pwd.isdigit() or pwd.isalpha():
            raise ValidationError("密码不能是纯数字或者纯字母")
        else:
            return pwd

    def clean_valid_code(self):

        val=self.cleaned_data.get("valid_code") # 用户输入的验证码

        if val.upper() == self.request.session.get("valid_code_str").upper():
            return self.cleaned_data.get("valid_code")

        else:
            raise ValidationError("valid code error！")


    def clean(self):
       if self.cleaned_data.get("pwd"):
           if self.cleaned_data.get("pwd") == self.cleaned_data.get("repeat_pwd"):
               return self.cleaned_data
           else:
               raise ValidationError("两次密码不一致！")

templates/NotFound.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
	<style type="text/css">
	body{margin:8% auto 0;max-width: 550px; min-height: 200px;padding:10px;font-family: Verdana,Arial,Helvetica,sans-serif;font-size:14px;}p{color:#555;margin:10px 10px;}img {border:0px;}.d{color:#404040;}
	</style>
</head>
<body>
<a href="http://www.cnblogs.com/"><img src="//static.cnblogs.com/images/logo_small.gif" alt="cnblogs"/></a>
<p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
<p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至contact&#64;cnblogs.com与我们联系。</p>
<p><a href="http://www.cnblogs.com/">返回网站首页</a></p>
</body>
</html>

templates/add_article.html
{% extends "backend.html" %}



{% block con %}

      <div class="article_con list-group">
          <a class="list-group-item active">文章添加</a>
          <form action="/backend/add_article/" method="post" class="list-group-item">
                  {% csrf_token %}
                 <h5>标题</h5>
                 <p><input type="text" name="title" class="form-control"></p>
                 <h5>内容</h5>
                 <p>
                     <textarea name="content" id="editor_id" cols="30" rows="10"></textarea>
                 </p>
                 <div class="panel panel-warning">

                 <div class="panel-heading">分类与标签</div>
                   <div class="panel-body">
                 <div class="panel panel-info">
                       <div class="panel-heading">网站分类</div>
                 <div class="panel-body">
                      {% for siteCategory in siteCategoryList %}
                       <p>{{ siteCategory.name }}：
                           {% for sitedetaicategory in siteCategory.sitedetaicategory_set.all %}
                               <input type="radio" name="site_cate" value="{{ sitedetaicategory.id }}">{{ sitedetaicategory.name }}
                           {% endfor %}

                       </p>
                      {% endfor %}
                 </div>
                 </div>
                   <div class="panel panel-danger">
                      <div  class="panel-heading">个人空间分类</div>
                   <div class="panel-body">
                 {% for cate in cate_list %}
                     <input type="radio" name="blog_cate" value="{{ cate.nid }}">{{ cate.title }}</input>
                 {% endfor %}
                   </div>
                   </div>
                   <div class="panel panel-success">
                 <div class="panel-heading">个人空间标签</div>
                   <div class="panel-body">
                 {% for tag in tag_list %}
                     <input type="checkbox" name="blog_tag" value="{{ tag.nid }}">{{ tag.title }}</input>
                 {% endfor %}
                   </div>
                    </div>
                   </div>
                 </div>
              <p><input type="submit" value="submit" class="btn btn-info"></p>
          </form>
      </div>


     <script>

           // 富文本编辑器
            KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    width:"870px",
                    height:"600px",
                    //items:[]
                    resizeType:1,
                    uploadJson:"/upload_img/",
                    extraFileUploadParams :{
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()

                    },
                    filePostName:"article_img"

                });
        });

     </script>
{% endblock %}

templates/base.html
{% block sidebar %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/static/dist/css/bootstrap.css" rel="stylesheet">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/dist/js/bootstrap.js"></script>
    <script src="http://code.jquery.com/jquery-1.12.3.min.js"></script>
    <link rel="icon" href="/static/img/iron-man.png">
<!-- 引入封装了failback的接口--initGeetest -->
<script src="http://static.geetest.com/static/tools/gt.js"></script>
    <link rel="stylesheet" href="/static/css/article.css">
    <link href="/static/sweetalert/sweetalert.css" rel="stylesheet">
    <script src="/static/sweetalert/sweetalert.min.js"></script>
    <link rel="stylesheet" href="/static/css/{{ blog.theme }}">
</head>

<body>

<div class="header container">
    <span class="user">{{ blog.title }}</span>
    {% if request.user.is_authenticated %}
        <div class="pull-right">
        <a href="/backend/{{ request.user }}" style="color: white;font-size: 20px">后台管理</a>
    <a href="/index/?user={{ request.user }}"  style="color: white;font-size: 20px">回到首页</a>
        </div>
{% else %}
        <div class="pull-right">
            <a href="/backendd/" style="color: white;font-size: 20px">后台管理</a>
    <a href="/index/" style="color: white;font-size: 20px">回到首页</a>
        </div>
        {% endif %}
</div>



<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">

                <div class="panel panel-warning">
                      <div class="panel-heading">公告</div>
                      <div class="panel-body">
                        Panel content
                      </div>
                </div>

                <div class="panel panel-danger">
                      <div class="panel-heading">随笔分类</div>
                      <div class="panel-body">
                        {% for cate in cate_list %}
                         <p><a href="/{{ username }}/cate/{{ cate.nid }}">{{ cate.title }}({{ cate.article_set.all.count }})</a></p>
                        {% endfor %}

                      </div>
                </div>

                 <div class="panel panel-danger">
                      <div class="panel-heading">我的标签</div>
                      <div class="panel-body">
                             {% for tag_info in tags_list %}
                                <p><a href="/{{ username }}/tag/{{ tag_info.2 }}">{{ tag_info.0 }}({{ tag_info.1 }})</a></p>
                             {% endfor %}

                      </div>
                </div>

                 <div class="panel panel-danger">
                      <div class="panel-heading">日期归档</div>
                      <div class="panel-body">
                             {% for date in date_list %}
                             <p><a href="/{{ username }}/archive/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a></p>
                             {% endfor %}


                      </div>
                </div>

        </div>
        <div class="col-lg-9">
               <div class="article_list">


                 {% block content %}{% endblock %}

            </div>
        </div>
<div style="text-align: center">
            <ul class="pagination">
                {% for item in page_fen %}
                {{ item|safe }}
                {% endfor %}

            </ul>
        </div>
    </div>


</body>
</html>
{% endblock %}

templates/edit_article.html
{% extends "backend.html" %}



{% block con %}

      <div class="article_con list-group">
          <a class="list-group-item active">文章编辑</a>
          <form action="/backend/edit_article/{{ ar.nid }}" method="post" class="list-group-item">
                  {% csrf_token %}
                 <h5>标题</h5>
                 <p><input type="text" name="title" class="form-control" value="{{ ar.title }}"></p>
                 <h5>内容</h5>
                 <p>
                     <textarea name="content" id="editor_id" cols="30" rows="10">
                         {{ ad.content }}
                     </textarea>
                 </p>
                 <div class="panel panel-warning">

                 <div class="panel-heading">分类与标签</div>
                   <div class="panel-body">
                 <div class="panel panel-info">
                       <div class="panel-heading">网站分类</div>
                 <div class="panel-body">
                      {% for siteCategory in siteCategoryList %}
                       <p>{{ siteCategory.name }}：
                           {% for sitedetaicategory in siteCategory.sitedetaicategory_set.all %}
                               {% if sitedetaicategory.id == ar.siteDetaiCategory.id%}
                               <input type="radio" name="site_cate" value="{{ sitedetaicategory.id }}" checked>{{ sitedetaicategory.name }}
                               {% else %}
                               <input type="radio" name="site_cate" value="{{ sitedetaicategory.id }}">{{ sitedetaicategory.name }}
                               {% endif %}
                           {% endfor %}

                       </p>
                      {% endfor %}
                 </div>
                 </div>
                   <div class="panel panel-danger">
                      <div  class="panel-heading">个人空间分类</div>
                   <div class="panel-body">
                 {% for cate in cate_list %}
                     {% if cate.nid == ar.homeCategory.nid%}
                     <input type="radio" name="blog_cate" value="{{ cate.nid }}" checked>{{ cate.title }}</input>
                     {% else %}
                     <input type="radio" name="blog_cate" value="{{ cate.nid }}">{{ cate.title }}</input>
                     {% endif %}
                 {% endfor %}
                   </div>
                   </div>
                   <div class="panel panel-success">
                 <div class="panel-heading">个人空间标签{{ ar.article2tag.tag_id.0 }}</div>
                   <div class="panel-body">
                 {% for tag in tag_list %}
                     {% if tag.nid == tas_id.tag_id%}
                     <input type="checkbox" name="blog_tag" value="{{ tag.nid }}" checked>{{ tag.title }}</input>
                     {% else %}
                     <input type="checkbox" name="blog_tag" value="{{ tag.nid }}">{{ tag.title }}</input>
                     {% endif %}
                 {% endfor %}
                   </div>
                    </div>
                   </div>
                 </div>
              <p><input type="submit" value="submit" class="btn btn-info"></p>
          </form>
      </div>


     <script>

           // 富文本编辑器
            KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    html : $('#editor_id').val(),
                    width:"870px",
                    height:"600px",
                    //items:[]
                    resizeType:1,
                    uploadJson:"/upload_img/",
                    extraFileUploadParams :{
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()

                    },
                    filePostName:"article_img"

                });
        });

     </script>
    <script>
    $.ajax({

    })
    </script>
{% endblock %}

templates/home_site.html
{% extends "base.html" %}

{% block content %}
   {% for article in article_list %}
                   <div class="article_item  dd">
                       <h3 class=" ee" ><a href="/{{ article.user.username }}/article/{{ article.nid }}" class="ac"><strong>{{ article.title }}</strong></a></h3>
                       <div class="row cd">
                           <a class="avatar_img col-md-2 " href="/{{ article.user.username }}/" ><img class="img-rounded tou" src="/media/{{ article.user.avatar }}" alt="" width="60" height="80"></a>
                           <div class="desc col-md-10">{{ article.desc }}</div>
                       </div>

                      <div class="info ee">
                          <a href="/{{ article.user.username }}/"><span>{{ article.user.username }}</span></a> &nbsp;&nbsp;
                          <span class="timer">{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;

                          <span class="glyphicon glyphicon-comment diantu"></span>&nbsp;<strong class="dian">评论({{ article.comment_count }})</strong>
                          <span class="glyphicon glyphicon-thumbs-up diantu"></span>&nbsp;<strong class="dian">点赞({{ article.up_count }})</strong>
                      </div>
                      <hr class="anb">
                  </div>
                {% endfor %}



{% endblock %}

templates/zhuce.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Title</title>
    <link href="/static/dist/css/bootstrap.css" rel="stylesheet">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/dist/js/bootstrap.js"></script>
     <link href="/static/sweetalert/sweetalert.css" rel="stylesheet">
    <script src="/static/sweetalert/sweetalert.min.js"></script>
    <link rel="icon" href="/static/img/iron-man.png">
</head>
<style>
    .dd{
{#        width:500px;#}
        height: 670px;
        border-radius: 20px 20px 20px 20px;
        position: fixed;
        box-shadow: 0px 0px 10px #7E7E7E;
        top:4%;
{#        left:33%;#}
    }
    body{
{#        background-color: #9d9d9d;#}
        background-image: url(/static/img/144.jpg);
    }
    .cd{
        width: 70%;
        margin-left: 60px;
    }
    .cee{
        margin-top: 20px;
        margin-left: 20px;
    }
    .cp{
{#        margin-left: 165px;#}
        font-size: 30px;
    }
    .error{
        height: 12px;
        width: 200px;
        font-size: 12px;
        color: #b92c28;
    }
    .ey{
        height: 12px;
        width: 200px;
        font-size: 12px;
        color: #b92c28;
    }
    .ddd{
        box-shadow: 0px 0px 10px #7E7E7E;
    }
    .ddd:hover{
        box-shadow: 0px 0px 10px #2b669a;
    }
</style>
<body>


<div class="container-fluid">
    <div class="row">

<div  class="dd col-md-4 col-md-offset-4" style="background-color: white">
    {% csrf_token %}

    <div class="cee">
   <div class="cp" style="text-align: center">用户注册</div>
  <div class="form-group cd">
    <label for="exampleInputUser">Username</label>
    <div class="input-group">
      <span class="glyphicon glyphicon-user input-group-addon" style="background-color: #2aabd2;color: white;"></span>
{#    <input type="text" class="form-control" id="exampleInputUser" placeholder="8~15位不能为纯英文或纯数字" name="user">#}
        {{ regForm.user }}
          </div>
  </div>
        <div id="user_error" class="cd error"></div>
  <div class="form-group cd">
    <label for="exampleInputPassword1">Password</label>
      <div class="input-group">
      <span class="glyphicon glyphicon-lock input-group-addon" style="background-color: #2aabd2;color: white;"></span>
{#    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="8~15位不能为纯英文或纯数字" name="pwd">#}
          {{ regForm.pwd }}
          </div>
  </div>
        <div id="pwd_error" class="cd error"></div>
        <div class="form-group cd">
    <label for="exampleInputPassword2">Password(again)</label>
      <div class="input-group">
      <span class="glyphicon glyphicon-lock input-group-addon" style="background-color: #2aabd2;color: white;"></span>
{#    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="再次输入密码" name="pwd">#}
          {{ regForm.repeat_pwd }}
          </div>
  </div>
        <div id="pwd2_error" class="cd error"></div>

        <div class="form-group cd">
    <label for="exampleInputEmail">Email</label>
      <div class="input-group">
      <span class="glyphicon glyphicon-lock input-group-addon" style="background-color: #2aabd2;color: white;"></span>
{#    <input type="email" class="form-control" id="exampleInputEmail" placeholder="Email地址" name="email">#}
          {{ regForm.email }}
          </div>
  </div>
        <div id="email_error" class="cd error"></div>
         <div class="form-group cd" style="margin-top: 10px">
    <label for="exampleInputFile">头像 <p><img id="touimg" title="图片格式推荐jpg" src="/static/default.jpg" alt="" width="50px" height="50px" class="img-circle ddd"></p></label>
    <input type="file" id="exampleInputFile" style="margin-left: 100px;display: none" name="img">
{#    <p class="help-block" style="margin-left: 100px">JPG格式图片</p>#}
  </div>
{#        <div id="img_error" class="cd error"></div>#}

{#        驗證碼#}

                  <div class="form-group" style="margin-left: 62px;margin-top: -10px">
                    <label for="valid_code">验证码</label>
                    <div class="row">
                        <div class="col-md-5">
{#                            <input type="text" class="form-control" id="valid_code" placeholder="valid_code">#}
                            {{ regForm.valid_code }}
                        </div>
                        <div class="col-md-5">
                            <img src="/get_valid_img/" width="150" height="34" id="valid_img" TITLE="点击刷新验证码">
                        </div>

                    </div>
 <div id="yzm" class="ey" ></div>
                  </div>


  <div class="cd">
      <button class="btn btn-warning btn-block tijiao">提交注册信息</button>
  </div>
</div>
</div>
    </div>
</div>


<script>
{#    $(".tijiao").click(function(){#}
{#         $("#user_error").text('').prev().removeClass("has-error");#}
{#         $("#pwd_error").text('').prev().removeClass("has-error");#}
{#         $("#yzm").text('').parent().parent().removeClass("has-error");#}
{#         $("#email_error").text('').prev().removeClass("has-error");#}
{#         $("#pwd2_error").text('').prev().removeClass("has-error");#}
{#         $("#img_error").text('').prev().removeClass("has-error");#}
{#        var username=$("#exampleInputUser").val();#}
{#        var pwd=$("#exampleInputPassword1").val();#}
{#        var pwd2=$("#exampleInputPassword2").val();#}
{#        var email=$("#exampleInputEmail").val();#}
{#        var valid_code=$("#valid_code").val();#}
{#        var img=$("#exampleInputFile")[0].files[0];#}
{##}
{#        var formData=new FormData();#}
{#        formData.append("user",username);#}
{#        formData.append("pwd",pwd);#}
{#        formData.append("pwd2",pwd2);#}
{#        formData.append("email",email);#}
{#        formData.append("valid_code",valid_code);#}
{#        formData.append("img",img);#}
{##}
{##}
{##}
{#        $.ajax({#}
{#            url:"/zhuce/",#}
{#            type:"POST",#}
{#            data:formData,#}
{#            contentType:false,#}
{#            processData:false,#}
{#            headers:{"X-CSRFToken":$('[name="csrfmiddlewaretoken"]').val()},#}
{#            success:function(data){#}
{#                dec=JSON.parse(data);#}
{#               if (dec.num==0){#}
{##}
{#                   $("#user_error").text(dec.error_user).prev().addClass("has-error");#}
{#                   $("#pwd_error").text(dec.error_pwd).prev().addClass("has-error");#}
{#               }#}
{#               else if(dec.num==1){#}
{#                        swal("注册成功", "即将跳转登录页面","success");#}
{#                        setTimeout(function () {#}
{#                             location.href="/index/"#}
{#                        },2000);#}
{#               }#}
{#                else if(dec.num==2){#}
{#                   $("#yzm").text(dec.error_yz).parent().parent().addClass("has-error")#}
{#               }#}
{#               else if(dec.num==3){#}
{#                   $("#email_error").text(dec.error_email).prev().addClass("has-error");#}
{#               }#}
{#               else if(dec.num==4){#}
{#                   $("#pwd2_error").text(dec.error_pwd2).prev().addClass("has-error");#}
{#               }#}
{#               else if(dec.num==5){#}
{#                   $("#img_error").text(dec.error_img)#}
{#               }#}
{##}
{#            }#}
{#        });#}


{#    });#}






$(".tijiao").click(function () {

        var $formData=new FormData();

        $formData.append("user",$("#id_user").val());
        $formData.append("pwd",$("#id_pwd").val());
        $formData.append("repeat_pwd",$("#id_repeat_pwd").val());
        $formData.append("email",$("#id_email").val());
        $formData.append("valid_code",$("#id_valid_code").val());
        var file=$("#exampleInputFile")[0].files[0];
        $formData.append("file_img",file);
        $formData.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url:"/zhuce/",
            type:"POST",
            data:$formData,
            processData:false,
            contentType:false,

            success:function (data) {
                //console.log(data);
                if (data.user){
                    swal("注册成功", "即将跳转登录页面","success");
                    setTimeout(function (){
                             location.href="/login/"
                        },2000);
                }
                else {
                    $(".error").text("").prev().removeClass("has-error");
                    $(".ey").text("").parent().parent().removeClass("has-error");
                    $(".form-group").removeClass("has-error");
{#                    console.log(data.errors);            // {"user":["",""],"pwd":["",""]}#}
                    $.each(data.errors,function (i,j) {   // i : 错误字段名称 j: 该字段所有错误列表
                          $("#id_"+i).parent().parent().addClass("has-error").next().css("color","red").text(j[0]);
                          if (i=="valid_code"){
                              $("#yzm").text(j[0]).parent().addClass("has-error")
                          }
                          if(i=="__all__"){
                              $("#id_repeat_pwd").parent().parent().addClass("has-error").next().css("color","red").text(j[0]);
                          }
                    })



                }

            }
        })


    });



    $("#exampleInputFile").change(function () {
{#        获取上传对象#}
        var file=$(this)[0].files[0];
{#        读取上传文件url#}
        var reader=new FileReader();
        reader.readAsDataURL(file);
        reader.onload=function () {
            $("#touimg").attr("src",this.result)
        }
    });
        $("#valid_img").click(function () {
         $(this)[0].src+="?"
     });


</script>
</body>
</html>